### ISSUE TITLE
issues of BGM_ADVANTAGE and BGM_DISADVANTAGE

### ISSUE THREAD

**Issue by purerosefallen** [mercury233/ygopro#2]
the bgm in BGM_ADVANTAGE should be played when i take advantage. and BGM_DISADVANTAGE be played when the opponent takes advantage
but actually, BGM_ADVANTAGE is played when the player who goes first takes advantage, while BGM_DISADVANTAGE played when the player who goes next takes.

**Comment by mercury233** [comment]
https://github.com/mercury233/ygopro/commit/6c067327eb339aba063e20b5bdf70438f75320ef
fixed
