### ISSUE TITLE
How to download the last version?

### ISSUE THREAD

**Issue by Septimoangel12** [mercury233/ygopro#24]
friend how to download Ygopro Core.exe and the last updates dec-2018 - Jun- 2019, thanks

**Comment by mercury233** [comment]
http://ygocore.ys168.com/

**Comment by Septimoangel12** [comment]
mercury233, hi friend, sorri but the page appears blank and does not give me a download link, why is this?

**Comment by mercury233** [comment]
It is for Chinese users so it may don't have good net connection for oversea users. You can try koishipro instead.

**Comment by Septimoangel12** [comment]
mercury233, I understand, I found this [Korean](https://cafe.naver.com/allygopro?iframe_url=/ArticleRead.nhn%3Fclubid=29286533%26menuid=9%26boardtype=L%26page=1%26specialmenutype=%26userDisplay=15%26articleid=897) page that has the download links, in addition, Koichi Ygopro does not have many new features that you have added to the console, thanks for your response and for the work that you do.
