### ISSUE TITLE
Add new Ygopro Percy codes

### ISSUE THREAD

**Issue by Septimoangel12** [mercury233/ygopro#26]
Hello **Mercury233**, finally they have released version 1.034.9, and it is great, thanks for the updates and corrections, as always one version is better than the previous one, I mainly wanted to thank you for having allowed us to add many of the cards that we worked on the project together with Ygopro Percy, thanks to that we could add many of the official Crds that came out in Videogames Manga and Anime of Yugioh, and we users of your game Ygopro Core are very grateful to you and maybe we will always be for allowing us and the rest of the players In the world of enjoying your game along with the **OCG** / **TCG** cards and this together with the oficial cards of format **ANIME**, **MANGA** and **VIDEO GAMES**, this makes the game totally different and evolved compared to other existing games.

I wanted to ask you please add the rest of the features that are still missing to implement in your game the total of almost all that we could add in **Ygopro Percy**, for this we added the following codes that some already work in the current version of **CORE** however there are many others I would like to ask you to add to the game, Ygopro Percy added the following codes to implement most of the official anime and manga videogames that we have been able to implement to date:

EFFECT_CANNOT_LOSE_DECK				=400
EFFECT_CANNOT_LOSE_LP				=401
EFFECT_CANNOT_LOSE_EFFECT			=402
EFFECT_BP_FIRST_TURN				        =403
EFFECT_UNSTOPPABLE_ATTACK			=404
EFFECT_ALLOW_NEGATIVE				=405
EFFECT_SELF_ATTACK					=406
EFFECT_BECOME_QUICK				        =407
EFFECT_LEVEL_RANK					=408
EFFECT_RANK_LEVEL					=409
EFFECT_LEVEL_RANK_S					=410
EFFECT_RANK_LEVEL_S					=411
EFFECT_UPDATE_LINK					=420
EFFECT_CHANGE_LINK					=421 
EFFECT_CHANGE_LINK_FINAL				=422
EFFECT_ADD_LINKMARKER				=423
EFFECT_REMOVE_LINKMARKER			=424
EFFECT_CHANGE_LINKMARKER			=425

So if you add the rest of the codes to be able to make compatible the card that we have implemented in Ygopro Percy, we will gladly share our work with you so that other Ygopro Core users can enjoy this type of game format, so you can give yourself a idea I can leave you the links of the projects that we work for Ygiopro Percy and you can know our work even at some time that you can try them and play them: 

**[My Missing Anime Cards Project Ygopro Percy](https://www.ygopro.co/Forum/tabid/95/g/posts/t/8185/My-Missing-Anime-Cards-Project#post48963)**

**[Septimoangel12 Anime Cards](https://www.deviantart.com/septimoangel12)** 

Thank you very much for your attention and for all the work you have done.

**Comment by purerosefallen** [comment]
Why don't you create Pull Requests to the Fluorohydride main repo with Percy's code? We would accept them as long as they really did something.
Also, it's hard for us to guess what is going on in YGOPro Percy.

**Comment by mercury233** [comment]
Thank you for your attention, but I'm afraid I can't do this. There are some reasons.
The official OCG effects aren't full implemented yet, such as _Contact "C"_, _Dai Dance_. **We** don't have enough time to work with the unofficial effects.
Most of the unofficial effects don't have ruling. I don't think it is a good idea to make judgement on our self.
Some effects are complex to implement and them may break the other part of the core, increase maintenance costs.

So personally I won't add unofficial effects to the YGOPro core.

-----
But there are some fork of the core which affect unofficial effects, such as https://github.com/purerosefallen/ygopro-core/blob/master/effect.h#L113

**Comment by Septimoangel12** [comment]
**purerosefallen**, **mercury233**, I understand, I know that adding new functions to add the Anime cards that have been left behind as (_Contact "C", Dai Dance, Mischief of the Time Goddess_, etc) and the new functions is something crazy, however that does not it means it's worth it, I know I'm talking to you through my Github account, however this has been an idea and asked by thousands of game users around the world, we like the game, and we appreciate all the effort they make, however the game has many adjustments to make, and those are solved by making a series of changes to CORE and make it more accessible to more functions, which only happens in original Manga and Anime story cards, maybe be difficult but if this is put to debate with the safe users all will access, for example a special donation by the users that would surely help them to add all the features of the game created not only by konami but by Autor of the Original idea on which they were based. Either way, it's just an idea, keep in mind that many would collaborate in it, thank you for your attention and for the work you do day by day, keep going with this project and many successes so that you can achieve it.
