### ISSUE TITLE
更換副卡組時觸發卡包展示模式

### ISSUE THREAD

**Issue by salix5** [mercury233/ygopro#30]
![bug](https://user-images.githubusercontent.com/2851577/179458198-05240491-80d5-402d-95b9-0d018cb60ae8.png)
![圖片](https://user-images.githubusercontent.com/2851577/179457871-6937eebf-ad48-4e69-9641-ba6b2001e250.png)

# 測試流程
IP連線對戰，X開房，Y加入
猜拳X贏，X選先攻

Y在投降按鈕出現時立刻按下
X進入換副卡組時出現上圖狀況
無法與副卡組的卡片交換

# 推測
1477本來應該是用在卡包展示模式
可能是在更換副卡組時觸發了卡包展示模式

**Comment by mercury233** [comment]
fixed in https://github.com/mercury233/ygopro/commit/940e3c5d6d7cbfbbb65968d0ea7fe22c7e3d784e
